jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: CaYa
        env:
          CYAPI: ${{ secrets.YTAPI }}
        run: |
          # API_KEY değişkenini kullanarak işlemler yapabilirsiniz
